### ISSUE TITLE
Needless sudo?

### ISSUE THREAD

**Issue by eitsupi** [stuartleeks/dev-container-features#3]
Thank you for publishing this wonderful feature!

I see sudo is used within the install script, but this script is assumed to be run as root, so probably unnecessary?
I also think sudo may not be installed in the base image.

> The install.sh script for each Feature should be executed as root during a container image build.

https://containers.dev/implementors/features/#invoking-installsh

https://github.com/stuartleeks/dev-container-features/blob/4ef7c8ae0a65fa242e30427aa425609b7de6a24e/src/shell-history/install.sh#L27

**Comment by stuartleeks** [comment]
Good point

When I looked at the script again, it wasn't clear to me whether the `sudo` calls added to `.bashrc` etc could be removed, but I've just tested with a new container/volume and it appears that they can!

**Comment by eitsupi** [comment]
Thanks for the quick update!

**Comment by stuartleeks** [comment]
Just realised that I had inadvertently picked up a cached feature definition in my tests. After re-running, it looks like the calls in the .bashrc etc are required so I'll revert part of the change I made
